language: python
python:
  - 3.3
  - 3.4
  - 3.5

before_install:
  - sudo apt-get update

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - chmod +x Miniconda3-latest-Linux-x86_64.sh
  - ./Miniconda3-latest-Linux-x86_64.sh
  - git clone https://github.com/udacity/CarND-Term1-Starter-Kit.git
  - cd CarND-Term1-Starter-Kit
  - conda env create -f environment.yml

before_script:
  - source activate carnd-term1
  
# Run test
script:
   - pytest
   
